server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  zipkin:
    base-url: http://192.168.95.128:9411
  sleuth:
    sampler:
      probability: 1
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: payment-route
        uri: lb://PAYMENTSERVER
        predicates:
          - Path=/payment/**
          - After=2021-06-02T22:56:47.431+08:00[Asia/Shanghai]
eureka:
  instance:
    instance-id: ${spring.application.name}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eurekaA:8001/eureka/
